// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAhK8gtmrxybw84dEyH3ddj6szaN5vBpY',
    appId: '1:158727618364:web:81a7e04426a8bf8d572839',
    messagingSenderId: '158727618364',
    projectId: 'yeohan-624f8',
    authDomain: 'yeohan-624f8.firebaseapp.com',
    databaseURL: 'https://yeohan-624f8-default-rtdb.firebaseio.com',
    storageBucket: 'yeohan-624f8.firebasestorage.app',
    measurementId: 'G-PW4Y10LK0C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD-znpxVxNrqZy3FaT0ecgBb9hVkTOKYA',
    appId: '1:158727618364:android:26283156b289b35e572839',
    messagingSenderId: '158727618364',
    projectId: 'yeohan-624f8',
    databaseURL: 'https://yeohan-624f8-default-rtdb.firebaseio.com',
    storageBucket: 'yeohan-624f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqLzdxqODqLGJldI4xfj5Zft3aso3WJ0E',
    appId: '1:158727618364:ios:e78742d60fb5b5f4572839',
    messagingSenderId: '158727618364',
    projectId: 'yeohan-624f8',
    databaseURL: 'https://yeohan-624f8-default-rtdb.firebaseio.com',
    storageBucket: 'yeohan-624f8.firebasestorage.app',
    iosBundleId: 'com.example.yeouidoParkingFlutter',
  );
}
